//fixture
export const START_FIXTURE_LOADING = 'START_FIXTURE_LOADING';
export const FINISH_FIXTURE_LOADING = 'FINISH_FIXTURE_LOADING';
export const SET_FIXTURE = 'SET_FIXTURE';
export const CLEAR_FIXTURE = 'CLEAR_FIXTURE';
export const SELECT_PLAYER = 'SELECT_PLAYER';


//mode
export const OPEN_COMMENTS = 'OPEN_COMMENTS';
export const CLOSE_COMMENTS = 'CLOSE_COMMENTS';


//club
export const START_CLUB_LOADING = 'START_CLUB_LOADING';
export const FINISH_CLUB_LOADING = 'FINISH_CLUB_LOADING';
export const SET_CLUB = 'SET_CLUB';
export const SET_CLUB_STATS = 'SET_CLUB_STATS';
export const CLEAR_CLUB_DATA = 'CLEAR_CLUB_DATA';
export const SET_CLUB_SQUAD = 'SET_CLUB_SQUAD';


//player
export const START_PLAYER_LOADING = 'START_PLAYER_LOADING';
export const FINISH_PLAYER_LOADING = 'FINISH_PLAYER_LOADING';
export const CLEAR_PLAYER_DATA = 'CLEAR_PLAYER_DATA';
export const SET_PLAYER_STATS = 'SET_PLAYER_STATS';
export const SET_PLAYER_TRANSFERS = 'SET_PLAYER_TRANSFERS';
export const SET_PLAYER_SIDELINES = 'SET_PLAYER_SIDELINES';
export const SET_AVAILIBLE_SEASONS = 'SET_AVAILIBLE_SEASONS';
export const SET_PLAYER_CLUB = 'SET_PLAYER_CLUB';
export const SET_PLAYER_PARTNERS = 'SET_PLAYER_PARTNERS';


//navbar
export const SET_LAST_LEAGUE = 'SET_LAST_LEAGUE';
export const SET_LAST_CLUB = 'SET_LAST_CLUB';
